spring:
  datasource:
    username: root
    password: toor
    druid:
      stat-view-servlet:
        login-username: root
        login-password: toor
swagger:
  enable: false
knife4j:
  production: true