spring:
  datasource:
    username: root
    password: toor
    druid.stat-view-servlet:
      login-username: root
      login-password: toor
springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false