spring:
  datasource:
    username: root
    password: toor
    druid:
      stat-view-servlet:
        login-username: root
        login-password: toor
logging:
  level:
    top.yinzsw.blog.mapper: debug
springdoc:
  packages-to-scan: top.yinzsw.blog.controller
  swagger-ui:
    tags-sorter: ALPHA
    operations-sorter: METHOD
  cache:
    disabled: true
openapi:
  title: "博客API文档"
  version: "@project.version@"
  description: "一个基于SpringBoot + Vue3的博客项目"
  contact-name: "yinzsW"
  contact-url: "https://github.com/yinzsw"
  contact-email: "yinzsW@qq.com"